### ISSUE TITLE
Add table for ML models & pipelines

### ISSUE THREAD

**Issue by mihow** [RolnickLab/ami-platform#309]
Consider adding a new tab on the project details page that lists ML pipelines. Then each pipeline has a detail pop-up with the model names, versions & descriptions. As well as a checkbox for "Active on this project".

**Comment by annavik** [comment]
Started to look into this! Is create, update and delete pipelines from web UI also relevant here? For create and update, it seems we only have the name for now on BE?

For the setting "Active on this project", how far do you think we are from having such an option on BE? :) Can we also add it as filter param on fetch, so that I can consider it where we present pipelines as dropdown options (for jobs, in session details)?

**Comment by mihow** [comment]
I did some thinking on this, let's make Pipelines & Algorithms read-only for now from the UI. Just show a table view and provide a details modal.

The pipelines now expose all of their attributes in the API and have a `stages[]` array that is the exactly same syntax as the new job stages array.

Pipelines
<img width="594" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/57719ac3-4d44-43e2-a48b-574364ade109">

Jobs
<img width="467" alt="image" src="https://github.com/RolnickLab/ami-platform/assets/158175/9abe9e4a-4c7a-477e-8a26-b4b3e90743e5">

The pipeline response also contains a list of nested Algorithm references. It would be helpful to show the name, version, description, updated_at of each algorithm. We could stuff that inline with the pipeline details, or make it's own table view.
