### ISSUE TITLE
Editing Storage description does not stick

### ISSUE THREAD

**Issue by LDalby** [RolnickLab/ami-platform#423]
When editing the storage description, you can fill out the field and click save, but it does not show on the page afterwards and the field is empty when click "Edit" afterwards. So it seems like the save doesn't really work. 

https://app.preview.insectai.org/projects/16

![image](https://github.com/RolnickLab/ami-platform/assets/2366579/ccb5f794-f963-4f0c-bf2d-55fe50f115f7)

Build c99d8af

**Comment by annavik** [comment]
Thanks for reporting! 🙏

**Comment by annavik** [comment]
@LDalby FIY we are currently working on some larger changes to storage sync, so be prepared on some changes here soon :)

**Comment by mihow** [comment]
@LDalby we ended up removing the storage description (actually it was never there in the backend!). I am hoping since the storage configs are specific to each project, the name can be long and informative enough for project owners. And it saves some room in the form since we added a bunch more fields. Are you okay with that?

<img width="719" alt="image" src="https://github.com/user-attachments/assets/70329bf4-caee-472c-ba76-cb872b98ccdd">
