### ISSUE TITLE
Show default sorting

### ISSUE THREAD

**Issue by annavik** [RolnickLab/ami-platform#430]
From start, we will not pass any sort param to BE and the order of items is not really specified. We could either just reflect the default sorting (whatever that is) in the interface OR make sure frontend always passes a sorting preference when items are fetched, also from start. Let me know what you prefer @mihow !

**Comment by annavik** [comment]
I'm thinking perhaps better to always specify a sorting preference from frontend, also from start? Just reflecting the default sorting will be a solution that means frontend app has to make assumptions.

**Comment by mihow** [comment]
I'm thinking the backend list views should return a meta attribute that contains the active filter and sorting parameters. Also then the filter parameter can be a full object with a name you can use for display, rather than just Event: 123

![image](https://github.com/RolnickLab/ami-platform/assets/158175/964d3a20-00e2-4c80-8bd5-0037b1cacfb4)

**Comment by mihow** [comment]
But ALSO, I think the default sorting preference can come from the UI. The backend list endpoints are used for multiple views. So it's really the current view/page that should store what sort order is most helpful in that context. I think the sort order for the Occurrences table view should default to the most recently detected occurrences.
